Repository team-sparta-a01-team-pr/sparta-bubble-club, pull requests merged in 2024-02, with the labels that each got.

#2 Docs: 이슈 및 PR 템플릿 적용
  .github/ISSUE_TEMPLATE/기능-등록-이슈-템플릿.md
  .github/ISSUE_TEMPLATE/리팩토링-등록-이슈-템플릿.md
  .github/ISSUE_TEMPLATE/문서-등록-이슈-템플릿.md
  .github/ISSUE_TEMPLATE/버그-등록-이슈-템플릿.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation, size/M

#3 Bugfix: 이슈 및 PR 템플릿 적용 수정
  .github/ISSUE_TEMPLATE/리팩토링-등록-이슈-템플릿.md
  .github/ISSUE_TEMPLATE/문서-등록-이슈-템플릿.md
  .github/ISSUE_TEMPLATE/버그-등록-이슈-템플릿.md
Labels: bugfix, size/XS

#5 Feat/#4 엔티티 기초 설정 추가
  src/main/kotlin/com/sparta/bubbleclub/domain/bubble/entity/Bubble.kt
  src/main/kotlin/com/sparta/bubbleclub/domain/member/entity/Member.kt
  src/main/kotlin/com/sparta/bubbleclub/global/config/JpaAuditingConfig.kt
  src/main/kotlin/com/sparta/bubbleclub/global/entity/BaseEntity.kt
Labels: size/M

#11 Feat: 회원가입 로그인 기능 추가
  build.gradle.kts
  src/main/kotlin/com/sparta/bubbleclub/domain/member/controller/MemberController.kt
  src/main/kotlin/com/sparta/bubbleclub/domain/member/dto/LoginRequest.kt
  src/main/kotlin/com/sparta/bubbleclub/domain/member/dto/LoginResponse.kt
  src/main/kotlin/com/sparta/bubbleclub/domain/member/dto/SignupRequest.kt
  src/main/kotlin/com/sparta/bubbleclub/domain/member/entity/Member.kt
  src/main/kotlin/com/sparta/bubbleclub/domain/member/repository/MemberRepository.kt
  src/main/kotlin/com/sparta/bubbleclub/domain/member/service/MemberService.kt
  src/main/kotlin/com/sparta/bubbleclub/global/config/PasswordEncoderConfig.kt
  src/main/kotlin/com/sparta/bubbleclub/global/security/SecurityConfig.kt
  src/main/kotlin/com/sparta/bubbleclub/global/security/jwt/JwtAuthenticationToken.kt
  src/main/kotlin/com/sparta/bubbleclub/global/security/jwt/JwtUtil.kt
  src/main/kotlin/com/sparta/bubbleclub/global/security/web/CustomAuthenticationEntryPoint.kt
  src/main/kotlin/com/sparta/bubbleclub/global/security/web/dto/MemberPrincipal.kt
  src/main/kotlin/com/sparta/bubbleclub/global/security/web/filter/JwtAuthenticationFilter.kt
Labels: feature, size/L

#10 Feat: Validation & Exception Handling 기능 추가
  src/main/kotlin/com/sparta/bubbleclub/global/exception/code/CommonErrorCode.kt
  src/main/kotlin/com/sparta/bubbleclub/global/exception/code/ErrorCode.kt
  src/main/kotlin/com/sparta/bubbleclub/global/exception/common/NoSuchEntityException.kt
  src/main/kotlin/com/sparta/bubbleclub/global/exception/handler/RestApiExceptionHandler.kt
  src/main/kotlin/com/sparta/bubbleclub/global/exception/response/ErrorResponse.kt
Labels: feature, size/L

#15 Refactor: 전역 예외 처리 기능 리팩토링
  src/main/kotlin/com/sparta/bubbleclub/global/exception/code/ErrorCode.kt
  src/main/kotlin/com/sparta/bubbleclub/global/exception/common/CommonErrorCode.kt
  src/main/kotlin/com/sparta/bubbleclub/global/exception/common/CustomIllegalArgumentException.kt
  src/main/kotlin/com/sparta/bubbleclub/global/exception/common/NoSuchEntityException.kt
  src/main/kotlin/com/sparta/bubbleclub/global/exception/common/RestApiException.kt
  src/main/kotlin/com/sparta/bubbleclub/global/exception/handler/RestApiExceptionHandler.kt
  src/main/kotlin/com/sparta/bubbleclub/global/exception/member/DuplicateArgumentException.kt
  src/main/kotlin/com/sparta/bubbleclub/global/exception/member/MemberErrorCode.kt
  src/main/kotlin/com/sparta/bubbleclub/global/exception/response/ErrorResponse.kt
Labels: size/L, refactor

#13 Refactor: 에러 메세지 한글로 변경
  src/main/kotlin/com/sparta/bubbleclub/domain/member/service/MemberService.kt
Labels: size/XS

#17 Refactor: Validation & Exception 처리 리팩토링
  src/main/kotlin/com/sparta/bubbleclub/domain/bubble/dto/request/CreateBubbleRequest.kt
  src/main/kotlin/com/sparta/bubbleclub/domain/bubble/dto/request/UpdateBubbleRequest.kt
  src/main/kotlin/com/sparta/bubbleclub/domain/bubble/service/BubbleService.kt
  src/main/kotlin/com/sparta/bubbleclub/domain/member/controller/MemberController.kt
  src/main/kotlin/com/sparta/bubbleclub/domain/member/dto/SignupRequest.kt
  src/main/kotlin/com/sparta/bubbleclub/domain/member/service/MemberService.kt
Labels: size/M, refactor

#22 Refactor: JWT 환경 변수 설정 리팩토링
  src/main/kotlin/com/sparta/bubbleclub/global/config/JwtPropertyConfig.kt
  src/main/kotlin/com/sparta/bubbleclub/global/security/jwt/JwtProperties.kt
  src/main/kotlin/com/sparta/bubbleclub/global/security/jwt/JwtUtil.kt
Labels: size/M, refactor

#24 Refactor: Bubble Pageable 리팩토링
  src/main/kotlin/com/sparta/bubbleclub/domain/bubble/controller/BubbleController.kt
Labels: size/XS, refactor

#25 Feat: 캐시 적용한 검색 기능 추가
  build.gradle.kts
  src/main/kotlin/com/sparta/bubbleclub/domain/bubble/controller/BubbleControllerV2.kt
  src/main/kotlin/com/sparta/bubbleclub/domain/bubble/service/BubbleService.kt
  src/main/kotlin/com/sparta/bubbleclub/global/config/CachingConfig.kt
  src/main/kotlin/com/sparta/bubbleclub/global/config/SwaggerConfig.kt
Labels: size/M, feature

#28 Refactor: Bubble 검색 기능 Pageable, bubbleId 파라미터 관련 리팩토링
  src/main/kotlin/com/sparta/bubbleclub/domain/bubble/controller/BubbleController.kt
  src/main/kotlin/com/sparta/bubbleclub/domain/bubble/controller/BubbleControllerV2.kt
  src/main/kotlin/com/sparta/bubbleclub/domain/bubble/repository/BubbleQueryDslRepositoryImpl.kt
  src/main/kotlin/com/sparta/bubbleclub/domain/bubble/service/BubbleService.kt
Labels: refactor, size/S

#30 Refactor: Bubble 단순 조회/검색 API 분리 리팩토링
  build.gradle.kts
  src/main/kotlin/com/sparta/bubbleclub/domain/bubble/controller/BubbleController.kt
  src/main/kotlin/com/sparta/bubbleclub/domain/bubble/controller/BubbleControllerV2.kt
  src/main/kotlin/com/sparta/bubbleclub/domain/bubble/dto/request/SearchKeywordRequest.kt
  src/main/kotlin/com/sparta/bubbleclub/domain/bubble/repository/BubbleQueryDslRepository.kt
  src/main/kotlin/com/sparta/bubbleclub/domain/bubble/repository/BubbleQueryDslRepositoryImpl.kt
  src/main/kotlin/com/sparta/bubbleclub/domain/bubble/service/BubbleService.kt
Labels: size/L, refactor

#32 Feat 인기검색어 목록 조회 및 저장기능 추가
  src/main/kotlin/com/sparta/bubbleclub/domain/bubble/entity/Bubble.kt
  src/main/kotlin/com/sparta/bubbleclub/domain/bubble/service/BubbleService.kt
  src/main/kotlin/com/sparta/bubbleclub/domain/keyword/controller/KeywordController.kt
  src/main/kotlin/com/sparta/bubbleclub/domain/keyword/dto/response/KeywordResponse.kt
  src/main/kotlin/com/sparta/bubbleclub/domain/keyword/entity/KeywordStore.kt
  src/main/kotlin/com/sparta/bubbleclub/domain/keyword/repository/KeywordQueryDslRepository.kt
  src/main/kotlin/com/sparta/bubbleclub/domain/keyword/repository/KeywordQueryDslRepositoryImpl.kt
  src/main/kotlin/com/sparta/bubbleclub/domain/keyword/repository/KeywordRepository.kt
  src/main/kotlin/com/sparta/bubbleclub/domain/keyword/service/KeywordService.kt
Labels: feature, size/L

#34 Bugfix: QKeywordStore Import 위치 버그 수정
  src/main/kotlin/com/sparta/bubbleclub/domain/keyword/repository/KeywordQueryDslRepositoryImpl.kt
Labels: bugfix, size/XS

#36 Refactor: 인기검색어 목록 조회 및 저장기능 리팩토링
  src/main/kotlin/com/sparta/bubbleclub/domain/bubble/controller/BubbleController.kt
  src/main/kotlin/com/sparta/bubbleclub/domain/bubble/controller/BubbleControllerV2.kt
  src/main/kotlin/com/sparta/bubbleclub/domain/bubble/dto/request/SearchKeywordRequest.kt
  src/main/kotlin/com/sparta/bubbleclub/domain/bubble/service/BubbleService.kt
  src/main/kotlin/com/sparta/bubbleclub/domain/keyword/controller/KeywordController.kt
  src/main/kotlin/com/sparta/bubbleclub/domain/keyword/service/KeywordService.kt
Labels: size/M, refactor

#38 Docs: README.md 내용 작성
  README.md
Labels: documentation, size/M

#40 Docs: README.md 패키지 구조 수정
  README.md
Labels: documentation, size/XS

#42 ✨ Feat: Redis 추가
  build.gradle.kts
  src/main/kotlin/com/sparta/bubbleclub/domain/bubble/controller/BubbleControllerV2.kt
  src/main/kotlin/com/sparta/bubbleclub/domain/bubble/dto/response/BubbleResponse.kt
  src/main/kotlin/com/sparta/bubbleclub/domain/bubble/dto/response/CustomSliceImpl.kt
  src/main/kotlin/com/sparta/bubbleclub/domain/bubble/repository/BubbleQueryDslRepository.kt
  src/main/kotlin/com/sparta/bubbleclub/domain/bubble/repository/BubbleQueryDslRepositoryImpl.kt
  src/main/kotlin/com/sparta/bubbleclub/domain/bubble/service/BubbleService.kt
  src/main/kotlin/com/sparta/bubbleclub/domain/keyword/dto/response/KeywordResponse.kt
  src/main/kotlin/com/sparta/bubbleclub/domain/keyword/service/KeywordService.kt
  src/main/kotlin/com/sparta/bubbleclub/domain/member/dto/SignupRequest.kt
  src/main/kotlin/com/sparta/bubbleclub/global/config/CachingConfig.kt
  src/main/kotlin/com/sparta/bubbleclub/global/config/PropertyConfig.kt
  src/main/kotlin/com/sparta/bubbleclub/global/config/RedisConfig.kt
  src/main/kotlin/com/sparta/bubbleclub/global/config/RedisProperties.kt
Labels: feature, size/L

#44 Reafactor/#43 패키지 구조 리팩토링
  README.md
  src/main/kotlin/com/sparta/bubbleclub/domain/bubble/dto/request/SearchKeywordRequest.kt
  src/main/kotlin/com/sparta/bubbleclub/domain/keyword/entity/KeywordStore.kt
  src/main/kotlin/com/sparta/bubbleclub/domain/keyword/service/KeywordService.kt
  src/main/kotlin/com/sparta/bubbleclub/domain/member/service/MemberService.kt
  src/main/kotlin/com/sparta/bubbleclub/global/cache/CachingConfig.kt
  src/main/kotlin/com/sparta/bubbleclub/global/entity/JpaAuditingConfig.kt
  src/main/kotlin/com/sparta/bubbleclub/global/property/PropertyConfig.kt
  src/main/kotlin/com/sparta/bubbleclub/global/schedule/SchedulingConfig.kt
  src/main/kotlin/com/sparta/bubbleclub/global/security/config/PasswordEncoderConfig.kt
  src/main/kotlin/com/sparta/bubbleclub/global/security/config/SecurityConfig.kt
  src/main/kotlin/com/sparta/bubbleclub/global/security/web/filter/JwtAuthenticationFilter.kt
  src/main/kotlin/com/sparta/bubbleclub/global/security/web/handler/CustomAuthenticationEntryPoint.kt
  src/main/kotlin/com/sparta/bubbleclub/infra/jwt/JwtAuthenticationToken.kt
  src/main/kotlin/com/sparta/bubbleclub/infra/jwt/JwtProperties.kt
  src/main/kotlin/com/sparta/bubbleclub/infra/jwt/JwtUtil.kt
  src/main/kotlin/com/sparta/bubbleclub/infra/querydsl/QueryDslSupport.kt
  src/main/kotlin/com/sparta/bubbleclub/infra/redis/RedisConfig.kt
  src/main/kotlin/com/sparta/bubbleclub/infra/redis/RedisProperties.kt
  src/main/kotlin/com/sparta/bubbleclub/infra/swagger/SwaggerConfig.kt
Labels: size/L, refactor

#46 Refactor: Redis 캐시 적용 리팩토링
  src/main/kotlin/com/sparta/bubbleclub/domain/bubble/service/BubbleService.kt
  src/main/kotlin/com/sparta/bubbleclub/domain/keyword/service/KeywordService.kt
  src/main/kotlin/com/sparta/bubbleclub/infra/redis/CacheKey.kt
  src/main/kotlin/com/sparta/bubbleclub/infra/redis/RedisConfig.kt
Labels: size/M, refactor

#51 Test: 테스트 코드 최초 설정
  build.gradle.kts
  src/test/kotlin/com/sparta/bubbleclub/domain/bubble/controller/BubbleControllerTest.kt
  src/test/kotlin/com/sparta/bubbleclub/domain/bubble/repository/BubbleRepositoryTest.kt
  src/test/kotlin/com/sparta/bubbleclub/domain/bubble/service/BubbleServiceTest.kt
  src/test/kotlin/com/sparta/bubbleclub/domain/keyword/controller/KeywordControllerTest.kt
  src/test/kotlin/com/sparta/bubbleclub/domain/keyword/repository/KeywordRepositoryTest.kt
  src/test/kotlin/com/sparta/bubbleclub/domain/keyword/service/KeywordServiceTest.kt
  src/test/kotlin/com/sparta/bubbleclub/domain/member/controller/MemberControllerTest.kt
  src/test/kotlin/com/sparta/bubbleclub/domain/member/repository/MemberRepositoryTest.kt
  src/test/kotlin/com/sparta/bubbleclub/domain/member/service/MemberServiceTest.kt
  src/test/kotlin/com/sparta/bubbleclub/fixture/bubble/BubbleFixture.kt
  src/test/kotlin/com/sparta/bubbleclub/fixture/keyword/KeywordFixture.kt
  src/test/kotlin/com/sparta/bubbleclub/fixture/member/MemberFixture.kt
  src/test/kotlin/com/sparta/bubbleclub/global/TestQueryDslConfig.kt
Labels: size/L, test

#53 Test: KeywordRepository getPopularKeywords() 테스트
  src/test/kotlin/com/sparta/bubbleclub/domain/keyword/repository/KeywordRepositoryTest.kt
  src/test/kotlin/com/sparta/bubbleclub/fixture/keyword/KeywordFixture.kt
Labels: size/M

#58 refactor: BubbleService 리팩토링
  src/main/kotlin/com/sparta/bubbleclub/domain/bubble/controller/BubbleController.kt
  src/main/kotlin/com/sparta/bubbleclub/domain/bubble/repository/BubbleQueryDslRepository.kt
  src/main/kotlin/com/sparta/bubbleclub/domain/bubble/repository/BubbleQueryDslRepositoryImpl.kt
  src/main/kotlin/com/sparta/bubbleclub/domain/bubble/service/BubbleService.kt
  src/main/kotlin/com/sparta/bubbleclub/global/exception/common/CommonErrorCode.kt
  src/main/kotlin/com/sparta/bubbleclub/global/exception/common/HasNoPermissionException.kt
  src/main/kotlin/com/sparta/bubbleclub/global/exception/handler/RestApiExceptionHandler.kt
Labels: size/M, refactor

#60 Test: Bubble 서비스 단위 테스트 작성
  src/main/kotlin/com/sparta/bubbleclub/domain/bubble/entity/Bubble.kt
  src/test/kotlin/com/sparta/bubbleclub/domain/bubble/repository/BubbleRepositoryTest.kt
  src/test/kotlin/com/sparta/bubbleclub/domain/bubble/service/BubbleServiceTest.kt
  src/test/kotlin/com/sparta/bubbleclub/fixture/bubble/BubbleFixture.kt
  src/test/kotlin/com/sparta/bubbleclub/fixture/common/CommonFixture.kt
Labels: size/L, test

#48 Feat: 자동 integration, deploy GitHub Actions 파일 추가
  .github/workflows/deploy.yml
  .github/workflows/integration.yml
  .gitignore
  src/test/kotlin/com/sparta/bubbleclub/SpartaBubbleClubApplicationTests.kt
Labels: feature, size/L

#63 Bugfix: deploy.yml 파일 수정
  .github/workflows/deploy.yml
Labels: bugfix, size/S

#64 Bugfix: deploy.yml 파일 수정
  .github/workflows/deploy.yml
Labels: bugfix, size/XS

#65 Bugfix/#62 deploy.yml 수정
  .github/workflows/deploy.yml
Labels: bugfix, size/XS
